version: '3'

tasks:
  deploy:
    dir: '{{.DIR}}'
    cmds:
      - export AWS_PROFILE={{.AWS_PROFILE}}
      - aws ecr get-login-password --region {{.AWS_REGION}} | docker login --username AWS --password-stdin {{.AWS_ECR_ID}}.dkr.ecr.{{.AWS_REGION}}.amazonaws.com
      - docker buildx build --platform=linux/amd64 -t {{.AWS_ECR_ID}}.dkr.ecr.{{.AWS_REGION}}.amazonaws.com/{{.NAME}}:{{.TAG}} .
      - docker push {{.AWS_ECR_ID}}.dkr.ecr.{{.AWS_REGION}}.amazonaws.com/{{.NAME}}:{{.TAG}}
    silent: true