name: 'Deploy'

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

permissions:
  id-token: write
  contents: read

jobs:
  build_push:
    uses: finddx/seq-treat-tbkb-github-workflows/.github/workflows/build_push.yml@main
    with:
      environment:  ${{ github.event.inputs.environment }}
      repo_name: ncbi-sync
      workdir: ./
    secrets: 
      AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}

